services:
  nginx:
    container_name: lunix-pro_nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:8080/tcp

  frontend:
    container_name: lunix-pro_frontend
    image: node:19-alpine
    volumes:
      - ../frontend:/opt/frontend
    working_dir: /opt/frontend
    command: npm run dev

  backend:
    container_name: lunix-pro_backend
    build:
      dockerfile: ../backend/Dockerfile.dev
      tags:
        - "lunix-pro_backend:latest"
    environment:
      - LP_API_URL=0.0.0.0:8081
    volumes:
      - ../backend:/opt/backend
      - ../db:/opt/db
      - ../manager:/opt/manager
      - ../Cargo.toml:/opt/Cargo.toml
      - ../Cargo.lock:/opt/Cargo.lock
      - ../target:/opt/target
